/// Slide deck schema, parser, and renderers (pure Dart, unit-tested).
///
/// The model is instructed to emit one fenced block:
/// ```slides
/// {"slides":[{"title":"...","points":["..."],"layout":"bullets",
///   "imagePrompt":"...","notes":"..."}]}
/// ```
/// `layout` is one of: title | bullets | image.
/// - Text-only models MUST still fill `imagePrompt` so the UI can reserve
///   a proper image box (placeholder) with the caption.
/// - Image-capable setups replace the placeholder with generated bytes.
/// Fallback: plain markdown split on `---` or `##` headings.
library;

import 'dart:convert';

/// One slide. [imageBytes] is filled post-generation (never from the model).
class Slide {
  String title;
  List<String> points;
  String layout; // title | bullets | image
  String imagePrompt;
  String notes;
  List<int>? imageBytes;

  Slide({
    required this.title,
    List<String>? points,
    String? layout,
    String? imagePrompt,
    String? notes,
    this.imageBytes,
  })  : points = points ?? [],
        layout = _normLayout(layout),
        imagePrompt = imagePrompt ?? '',
        notes = notes ?? '';

  static String _normLayout(String? l) {
    final v = (l ?? '').trim().toLowerCase();
    if (v == 'title' || v == 'bullets' || v == 'image') return v;
    return 'bullets';
  }

  factory Slide.fromMap(Map m) => Slide(
        title: (m['title'] ?? '').toString(),
        points: (m['points'] is List)
            ? (m['points'] as List).map((e) => e.toString()).toList()
            : [],
        layout: (m['layout'] ?? '').toString(),
        imagePrompt: (m['imagePrompt'] ?? '').toString(),
        notes: (m['notes'] ?? '').toString(),
      );

  Map<String, dynamic> toMap() => {
        'title': title,
        'points': points,
        'layout': layout,
        'imagePrompt': imagePrompt,
        'notes': notes,
      };

  bool get wantsImage =>
      layout == 'image' ||
      (layout == 'bullets' && imagePrompt.trim().isNotEmpty);
}

/// Extract the fenced ```slides (or ```json holding "slides") payload.
String? extractSlidesJson(String raw) {
  final fence = RegExp(r'```(\w*)\n([\s\S]*?)```');
  for (final m in fence.allMatches(raw)) {
    final tag = (m.group(1) ?? '').toLowerCase();
    final body = (m.group(2) ?? '').trim();
    if (tag == 'slides') return body;
    if ((tag == 'json' || tag.isEmpty) && body.contains('"slides"')) {
      return body;
    }
  }
  // Unfenced fallback: raw JSON object containing "slides".
  final t = raw.trim();
  if (t.startsWith('{') && t.contains('"slides"')) return t;
  return null;
}

/// Parse model output into slides. Never throws, never empty on valid-ish
/// input (falls back to one slide with the raw text).
List<Slide> parseSlides(String raw) {
  final out = <Slide>[];
  try {
    final payload = extractSlidesJson(raw);
    if (payload != null) {
      final decoded = jsonDecode(payload);
      final list = decoded is Map
          ? decoded['slides']
          : (decoded is List ? decoded : null);
      if (list is List) {
        for (final s in list.whereType<Map>()) {
          final slide = Slide.fromMap(s);
          if (slide.title.trim().isEmpty &&
              slide.points.isEmpty &&
              slide.imagePrompt.trim().isEmpty) {
            continue;
          }
          out.add(slide);
        }
      }
      if (out.isNotEmpty) return out;
    }
  } catch (_) {}
  // Markdown fallback: split on --- rules or ## headings.
  return _parseMarkdownSlides(raw);
}

List<Slide> _parseMarkdownSlides(String raw) {
  // Strip any fenced code first (already tried as JSON above).
  var text = raw.replaceAll(RegExp(r'```[\s\S]*?```'), '').trim();
  if (text.isEmpty) {
    return [Slide(title: 'Untitled', points: [])];
  }
  final chunks = text
      .split(RegExp(r'^\s*---+\s*$', multiLine: true))
      .map((e) => e.trim())
      .where((e) => e.isNotEmpty)
      .toList();
  final slides = <Slide>[];
  for (final chunk in chunks) {
    String title = '';
    final points = <String>[];
    for (final line in chunk.split('\n')) {
      final t = line.trim();
      if (t.isEmpty) continue;
      if (title.isEmpty && (t.startsWith('#'))) {
        title = t.replaceAll(RegExp(r'^#+\s*'), '');
      } else if (t.startsWith(RegExp(r'[-*•]\s+'))) {
        points.add(t.replaceFirst(RegExp(r'^[-*•]\s+'), ''));
      } else if (title.isEmpty) {
        title = t.length > 80 ? '${t.substring(0, 80)}…' : t;
      } else {
        points.add(t);
      }
    }
    if (title.isEmpty && points.isEmpty) continue;
    slides.add(Slide(
      title: title.isEmpty ? 'Untitled' : title,
      points: points,
    ));
  }
  if (slides.isEmpty) {
    return [Slide(title: 'Untitled', points: [text])];
  }
  return slides;
}

/// System prompt for deck generation. [count] slides, [style] tone.
String slideSystemPrompt({required int count, required String style}) {
  return '''You are a presentation designer. Output EXACTLY one fenced block and nothing else:

```slides
{"slides":[{"title":"...","points":["..."],"layout":"bullets","imagePrompt":"...","notes":"..."}]}
```

Rules:
- Produce exactly $count slides. First slide layout "title" (topic + subtitle point). Others "bullets" (3-5 short points) or "image" (1-2 points + visual).
- "points" are short display lines, never paragraphs. No markdown inside fields.
- EVERY content slide MUST include "imagePrompt": a vivid one-sentence visual for that slide. Text-only pipelines reserve a proper image box from it; image-capable pipelines may render it. Never leave it empty on "image" layout.
- "notes" is one optional speaker-note sentence (may be empty).
- Tone/style: $style.
- If you can call tools (image search/fetch) to ground facts or visuals, use them freely.
- Valid JSON only inside the fence. No prose outside.''';
}

/// Single-slide regeneration user prompt.
String slideRegenPrompt({
  required String topic,
  required int index, // 1-based
  required Slide current,
}) {
  final cur = current.points.map((p) => '- $p').join('\n');
  return '''Regenerate ONLY slide $index of the "$topic" deck. Keep the same JSON shape with keys title/points/layout/imagePrompt/notes inside one ```slides fence and nothing else.

Current slide:
Title: ${current.title}
$cur
Layout: ${current.layout}
Image: ${current.imagePrompt}

Make it sharper and better formatted; keep it on-topic as slide $index.''';
}

/// Deck → Markdown (export + PDF source).
String deckToMarkdown(String topic, List<Slide> slides) {
  final buf = StringBuffer('# $topic\n\n');
  for (var i = 0; i < slides.length; i++) {
    final s = slides[i];
    buf.writeln('## ${i + 1}. ${s.title}\n');
    for (final p in s.points) {
      buf.writeln('- $p');
    }
    if (s.imagePrompt.trim().isNotEmpty) {
      buf.writeln('\n> Image: ${s.imagePrompt.trim()}');
    }
    if (s.notes.trim().isNotEmpty) {
      buf.writeln('\n_Notes: ${s.notes.trim()}_');
    }
    buf.writeln('\n---\n');
  }
  return buf.toString();
}

/// Deck → standalone styled HTML presentation (export + preview).
String deckToHtml(String topic, List<Slide> slides) {
  String esc(String s) => s
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;');
  final buf = StringBuffer('''<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(topic)}</title>
<style>
:root{color-scheme:light dark}
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:'Segoe UI',system-ui,sans-serif;background:#14141c;color:#f2f0ea}
.slide{min-height:100vh;display:flex;flex-direction:column;justify-content:center;padding:8vh 8vw;border-bottom:1px solid #33334d;page-break-after:always}
.kicker{color:#d97757;font-weight:800;letter-spacing:3px;font-size:13px;margin-bottom:12px}
h1{font-size:clamp(28px,5vw,54px);line-height:1.15;margin-bottom:18px}
h2{font-size:clamp(22px,3.6vw,38px);margin-bottom:16px}
ul{list-style:none;display:flex;flex-direction:column;gap:12px;font-size:clamp(15px,2.2vw,22px);line-height:1.5}
ul li{padding-left:26px;position:relative}
ul li::before{content:'▸';position:absolute;left:0;color:#d97757}
.ph{margin-top:22px;border:2px dashed #d97757;border-radius:14px;padding:28px;text-align:center;color:#c9c4bb;font-size:14px}
.ph b{display:block;color:#d97757;margin-bottom:6px;letter-spacing:1px;font-size:12px}
.notes{margin-top:18px;font-size:13px;font-style:italic;color:#9a958c}
.num{position:fixed;right:18px;bottom:14px;color:#6a675f;font-size:12px}
@media print{.slide{min-height:95vh;border:none}.num{display:none}}
</style></head><body>
''');
  for (var i = 0; i < slides.length; i++) {
    final s = slides[i];
    buf.writeln('<section class="slide">');
    buf.writeln('<div class="kicker">${i + 1} / ${slides.length}</div>');
    if (s.layout == 'title' && i == 0) {
      buf.writeln('<h1>${esc(s.title)}</h1>');
    } else {
      buf.writeln('<h2>${esc(s.title)}</h2>');
    }
    if (s.points.isNotEmpty) {
      buf.writeln('<ul>');
      for (final p in s.points) {
        buf.writeln('<li>${esc(p)}</li>');
      }
      buf.writeln('</ul>');
    }
    if (s.imagePrompt.trim().isNotEmpty) {
      buf.writeln(
          '<div class="ph"><b>IMAGE</b>${esc(s.imagePrompt.trim())}</div>');
    }
    if (s.notes.trim().isNotEmpty) {
      buf.writeln('<div class="notes">${esc(s.notes.trim())}</div>');
    }
    buf.writeln('</section>');
  }
  buf.writeln('<div class="num">${esc(topic)}</div></body></html>');
  return buf.toString();
}
